"""Serve or export the target-blind Needle Lens runtime certificate.

Every customer turn is generated by the unmodified official public simulator.
Every agent response comes from the selected primary. The trace attached to a
turn is emitted by that same Agent call and never receives ground truth.

    python scripts/needle_lens.py
    python scripts/needle_lens.py --export .artifacts/demo/needle-lens.json
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import threading
import time
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse


ROOT = Path(__file__).resolve().parents[1]
KIT = Path(
    os.environ.get(
        "TECHJAM_KIT_ROOT",
        ROOT / ".artifacts" / "participant-kit" / "techjam-conversational-search",
    )
)
ASSET = ROOT / ".artifacts" / "indexes" / "catalog-signatures.sqlite3"
HTML = ROOT / "demo" / "needle-lens.html"
sys.path.insert(0, str(ROOT))
sys.path.insert(1, str(KIT))

from evaluator import local_evaluator as official  # noqa: E402

from needle.agent import Agent  # noqa: E402
from needle.presets import PRIMARY_AGENT_KWARGS  # noqa: E402


class LensFactory:
    """Official-simulator session source with bounded in-process caching."""

    def __init__(self) -> None:
        self.catalog_path = KIT / "data" / "catalog.jsonl"
        self.dataset_path = KIT / "data" / "public_set.jsonl"
        missing = [
            str(path)
            for path in (self.catalog_path, self.dataset_path, HTML)
            if not path.is_file()
        ]
        if missing:
            raise FileNotFoundError(
                "needle lens prerequisites are missing: " + ", ".join(missing)
            )
        self.samples = official.load_jsonl(self.dataset_path)
        self.by_id = {str(sample["sample_id"]): sample for sample in self.samples}
        self.catalog_ids, self.categories, self.products = official.catalog_index(
            self.catalog_path
        )
        self._cache: dict[str, dict[str, object]] = {}
        self._lock = threading.Lock()

    def sample_index(self) -> dict[str, object]:
        grouped: dict[str, list[dict[str, str]]] = {}
        for sample in self.samples:
            grouped.setdefault(str(sample["scenario_type"]), []).append({
                "sample_id": str(sample["sample_id"]),
                "difficulty": str(sample.get("difficulty_bucket", "unknown")),
            })
        return {
            "scenarios": grouped,
            "default_sample": next(
                sample["sample_id"]
                for sample in self.samples
                if sample["scenario_type"] == "intent_override"
            ),
        }

    def run(self, sample_id: str) -> dict[str, object]:
        try:
            sample = self.by_id[sample_id]
        except KeyError as error:
            raise ValueError(f"unknown public sample: {sample_id}") from error
        with self._lock:
            cached = self._cache.get(sample_id)
        if cached is not None:
            return cached

        agent_kwargs = {**PRIMARY_AGENT_KWARGS, "trace_enabled": True}
        if ASSET.is_file():
            agent_kwargs["signature_index_path"] = ASSET
        agent = Agent(self.catalog_path, **agent_kwargs)
        session_id = f"lens_{sample_id}"
        agent.reset(session_id, sample["user_profile"])

        target = str(sample["ground_truth"]["parent_asin"])
        card, behavior = official.materialize_hidden_fields(sample, self.products)
        effective = {**sample, "intent_card": card, "behavior": behavior}
        disclosed: set[str] = set()
        boundary_used = False
        override_applied = sample["scenario_type"] != "intent_override"
        customer_message = official.initial_message(
            effective,
            official.coarse_category(self.categories.get(target, [])),
            disclosed,
        )
        turns: list[dict[str, object]] = []
        hit_turn: int | None = None
        hit_rank: int | None = None
        try:
            for turn in range(1, official.MAX_TURNS + 1):
                started = time.perf_counter()
                response = agent.respond(
                    session_id,
                    customer_message,
                    turn,
                    official.TOP_K,
                )
                latency_ms = (time.perf_counter() - started) * 1000.0
                ranked = official.normalize_recommendations(
                    response.get("recommendations"), self.catalog_ids
                )
                trace = agent.trace_for(session_id)[-1]
                hit = override_applied and target in ranked
                rank = ranked.index(target) + 1 if hit else None
                turns.append({
                    "turn": turn,
                    "customer_message": customer_message,
                    "scorable": override_applied,
                    "hit": hit,
                    "hit_rank": rank,
                    "latency_ms": round(latency_ms, 3),
                    "response": response,
                    "trace": trace,
                })
                if hit:
                    hit_turn = turn
                    hit_rank = rank
                    break
                if turn == official.MAX_TURNS:
                    break
                override = effective.get("behavior", {}).get("override") or {}
                if not override_applied and turn + 1 == int(override.get("turn", 3)):
                    override_applied = True
                    new_value = str(override.get("new_value", ""))
                    if new_value:
                        disclosed.add(new_value)
                    customer_message = str(
                        override.get(
                            "message",
                            "Actually, please ignore my earlier preference.",
                        )
                    )
                else:
                    customer_message, boundary_used = official.customer_reply(
                        effective,
                        response.get("ask_attribute"),
                        disclosed,
                        boundary_used,
                    )
        finally:
            agent.close()

        target_product = self.products[target]
        session_score = 0.0
        if hit_turn is not None and hit_rank is not None:
            session_score = (
                0.50
                + 0.30 / hit_rank
                + 0.20 * (11.0 - hit_turn) / 10.0
            )
        payload: dict[str, object] = {
            "mode": "official-public-replay",
            "trace_target_blind": True,
            "sample_id": sample_id,
            "scenario_type": str(sample["scenario_type"]),
            "difficulty_bucket": str(sample.get("difficulty_bucket", "unknown")),
            "catalog_size": len(self.catalog_ids),
            "result": {
                "hit": hit_turn is not None,
                "first_hit_turn": hit_turn,
                "rank": hit_rank,
                "session_score": round(session_score, 6),
                # Ground truth belongs to this evaluator-owned envelope, never
                # to a turn trace or Agent input. The UI reveals it only after
                # the replay reaches a scored hit.
                "target": {
                    "parent_asin": target,
                    "title": str(target_product.get("title") or ""),
                },
            },
            "turns": turns,
            "disclosures": {
                "network": "disabled",
                "model": "none",
                "prompt_tokens": 0,
                "completion_tokens": 0,
                "trace_influences_ranking": False,
                "human_question_board_influences_scored_policy": False,
            },
        }
        with self._lock:
            if len(self._cache) >= 8:
                self._cache.pop(next(iter(self._cache)))
            self._cache[sample_id] = payload
        return payload


class LensHandler(BaseHTTPRequestHandler):
    factory: LensFactory
    html: bytes

    def _send(self, status: HTTPStatus, body: bytes, content_type: str) -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header(
            "Content-Security-Policy",
            "default-src 'self'; style-src 'unsafe-inline'; "
            "script-src 'unsafe-inline'; connect-src 'self'",
        )
        self.end_headers()
        self.wfile.write(body)

    def _json(self, status: HTTPStatus, payload: object) -> None:
        self._send(
            status,
            json.dumps(payload, separators=(",", ":"), ensure_ascii=False).encode("utf-8"),
            "application/json; charset=utf-8",
        )

    def do_GET(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler contract
        parsed = urlparse(self.path)
        try:
            if parsed.path == "/":
                self._send(HTTPStatus.OK, self.html, "text/html; charset=utf-8")
                return
            if parsed.path == "/api/samples":
                self._json(HTTPStatus.OK, self.factory.sample_index())
                return
            if parsed.path == "/api/session":
                sample_id = parse_qs(parsed.query).get("sample_id", [""])[0]
                self._json(HTTPStatus.OK, self.factory.run(sample_id))
                return
            self._json(HTTPStatus.NOT_FOUND, {"error": "not found"})
        except ValueError as error:
            self._json(HTTPStatus.BAD_REQUEST, {"error": str(error)})
        except Exception as error:  # noqa: BLE001 - local demo must report, not die
            self._json(
                HTTPStatus.INTERNAL_SERVER_ERROR,
                {"error": f"{type(error).__name__}: {error}"},
            )

    def log_message(self, format: str, *args: object) -> None:
        print(f"lens {self.address_string()} {format % args}")


def main() -> None:
    parser = argparse.ArgumentParser(description="serve the Needle Lens judge console")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--sample", default=None)
    parser.add_argument("--export", type=Path, default=None)
    arguments = parser.parse_args()

    factory = LensFactory()
    sample_id = arguments.sample or str(factory.sample_index()["default_sample"])
    if arguments.export is not None:
        payload = factory.run(sample_id)
        arguments.export.parent.mkdir(parents=True, exist_ok=True)
        arguments.export.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        print(arguments.export.resolve())
        return

    handler = type(
        "ConfiguredLensHandler",
        (LensHandler,),
        {"factory": factory, "html": HTML.read_bytes()},
    )
    server = ThreadingHTTPServer((arguments.host, arguments.port), handler)
    print(f"needle lens: http://{arguments.host}:{arguments.port}")
    print("ctrl+c to stop")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
